[DATA]
link = 'https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv'

[MODELS]
random_forest = 'model/conf/random_forest_model.pkl'
neural_networks = 'model/conf/neural_networks_model.pkl'

[TARGET]
target = 'target'

[PARAMS]
cv = 10

[TUNING]
NeuralNetworks = {"activation"= ['tanh', 'relu'], "alpha"= [0.0001, 1.0, 100], 'max_iter'= [2000], 'hidden_layer_sizes'= [1, 10, 100]}
RandomForest = {"max_depth"= [1, 3, 5, 7], "bootstrap"= [true, false], 'min_samples_split'= [2, 5]}